# 代码运行的环境平台
language: php

# 代码测试的语言版本
php:
    - 7.3

# 系统版本
dist: trusty

# 是否使用 sudo 模式
sudo: false

# 执行前需要运行的命令
install: travis_retry composer install --no-interaction --prefer-source

# 主要构建命令
script: vendor/bin/phpunit --verbose